name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Add Inkscape PPA
      run: sudo add-apt-repository ppa:inkscape.dev/stable-0.92
    - name: Update APT
      run: sudo apt update
    - name: Install Inkscape
      run: sudo apt install inkscape
    - name: Install NPM Dependencies
      run: npm install
    - name: Build
      run: npm run build
