name: Build

on:
  push:
    branches: '**'
    tags-ignore: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install NPM Dependencies
      run: npm install
    - name: Build
      run: npm run build:all
